server.port=${SERVER_PORT:8081}
spring.application.name=smart-apply-ai
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER:http://localhost:5000/realms/master}
service.security.allowed-origins=${ALLOWED_ORIGINS:http://localhost:8080}

# Enable actuator & prometheus(Monitoring)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Kafka broker
spring.kafka.bootstrap-servers=${KAFKA_URL:localhost:9092}
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.json.use.type.headers=false

kafka.topic.ai.resume-analysis=ai-resume-analysis
kafka.topic.ai.qa=ai-questions-answers

# MCP
service.mcp.server-url=${MCP_SERVER_URL:http://localhost:8080}

# Langchain4j
langchain4j.open-ai.streaming-chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.streaming-chat-model.model-name=gpt-5
langchain4j.open-ai.streaming-chat-model.timeout=5m

# https://docs.langchain4j.dev/integrations/language-models/open-ai

